services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      APP_PORT: 8080
      PG_DB_URL: host.docker.internal
      PG_DB_PORT: 5432
      PG_DB_NAME: appdb
      PG_DB_USERNAME: admin
      PG_DB_PASSWORD: test
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8081:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    depends_on:
      - backend
    ports:
      - "8080:80"
